const VERSION='0.6';
const STORAGE='gefuehlskompass-prototype-catalog-v03';
const ENTRIES='gefuehlskompass-prototype-entries-v03';

const defaults={
  situations:[
    {name:'Zuhause',hint:'Wohnung, Haus oder eigener Rückzugsort'},
    {name:'Arbeit',hint:'Arbeitsplatz, Besprechung oder berufliche Aufgabe'},
    {name:'Unterwegs',hint:'S-Bahn, Auto, zu Fuß oder beim Einkauf'},
    {name:'Familie',hint:'Kontakt oder Situation mit Familie'},
    {name:'Freunde',hint:'Kontakt oder Situation mit Freund:innen'},
    {name:'Freizeit',hint:'Hobby, Medien, Sport oder Erholung'},
    {name:'Gesundheit / Behandlung',hint:'Arzttermin, Therapie, Beschwerden, Medikamente oder Pflege'},
    {name:'Sonstiges',hint:'Anderen Kontext selbst eingeben'}
  ],
  body:['Schmerz','Druck','Schwere','Wärme','Kälte','Müdigkeit','Hunger','Durst','Unruhe','Anspannung','Entspannung','Leichtigkeit','Kribbeln'],
  regions:['Kopf','Kiefer','Nacken','Schultern','Brust','Bauch','Rücken','Arme','Hände','Beine','ganzer Körper'],
  impulses:['Bleiben','Weggehen','Schlafen','Mich verstecken','Reden','Allein sein','Nähe suchen','Weinen','Etwas verändern','Widersprechen','Bewegen','Nichts tun'],
  needs:['Ruhe','Sicherheit','Nähe','Abstand','Bewegung','Essen','Schlaf','Struktur','Unterstützung','Verständnis','Ablenkung','Zeit für mich'],
  main:[
    {name:'Freude',color:'#77a982'},
    {name:'Angst',color:'#c77b77'},
    {name:'Scham',color:'#c89aaa'},
    {name:'Ekel',color:'#d69c67'},
    {name:'Trauer',color:'#9383ad'},
    {name:'Ärger',color:'#789eb5'},
    {name:'Schuld',color:'#cfbd66'}
  ],
  sub:[
    {name:'zufrieden',main:'Freude',body:['Leichtigkeit','Wärme'],valence:'angenehm',energy:'mittel',arousal:'ruhig',impulses:['Bleiben']},
    {name:'geborgen',main:'Freude',body:['Wärme','Leichtigkeit'],valence:'angenehm',energy:'wenig',arousal:'ruhig',impulses:['Nähe suchen','Bleiben']},
    {name:'interessiert',main:'Freude',body:['Kribbeln'],valence:'angenehm',energy:'mittel',arousal:'ruhig',impulses:['Bleiben']},
    {name:'angespannt',main:'Angst',body:['Anspannung','Druck','Schmerz'],valence:'unangenehm',energy:'mittel',arousal:'angespannt',impulses:['Weggehen','Etwas verändern']},
    {name:'unsicher',main:'Angst',body:['Unruhe','Druck'],valence:'unangenehm',energy:'mittel',arousal:'aufgewühlt',impulses:['Mich verstecken','Nähe suchen']},
    {name:'überfordert',main:'Angst',body:['Schmerz','Druck','Schwere'],valence:'unangenehm',energy:'wenig',arousal:'aufgewühlt',impulses:['Weggehen','Allein sein']},
    {name:'gereizt',main:'Ärger',body:['Anspannung','Schmerz','Wärme'],valence:'unangenehm',energy:'mittel',arousal:'angespannt',impulses:['Widersprechen','Etwas verändern']},
    {name:'frustriert',main:'Ärger',body:['Druck','Anspannung'],valence:'unangenehm',energy:'mittel',arousal:'angespannt',impulses:['Etwas verändern','Widersprechen']},
    {name:'bedrückt',main:'Trauer',body:['Schwere','Müdigkeit','Druck'],valence:'unangenehm',energy:'wenig',arousal:'ruhig',impulses:['Weinen','Allein sein']},
    {name:'traurig',main:'Trauer',body:['Schwere','Müdigkeit'],valence:'unangenehm',energy:'wenig',arousal:'ruhig',impulses:['Weinen','Nähe suchen']},
    {name:'unglücklich',main:'Trauer',body:['Schwere','Müdigkeit'],valence:'unangenehm',energy:'wenig',arousal:'ruhig',impulses:['Allein sein','Nähe suchen']},
    {name:'peinlich berührt',main:'Scham',body:['Wärme','Anspannung','Kribbeln'],valence:'unangenehm',energy:'mittel',arousal:'aufgewühlt',impulses:['Mich verstecken','Weggehen']},
    {name:'beschämt',main:'Scham',body:['Wärme','Schwere'],valence:'unangenehm',energy:'wenig',arousal:'angespannt',impulses:['Mich verstecken']},
    {name:'schuldig',main:'Schuld',body:['Druck','Schwere'],valence:'unangenehm',energy:'wenig',arousal:'angespannt',impulses:['Etwas verändern','Reden']},
    {name:'angewidert',main:'Ekel',body:['Unruhe','Kälte'],valence:'unangenehm',energy:'mittel',arousal:'angespannt',impulses:['Weggehen']}
  ]
};

let catalog=loadJson(STORAGE,structuredClone(defaults));
let entries=loadJson(ENTRIES,[]);
let page='dialog';
let step=1;
let showAllMainFeelings=false;
let showAllSubs=false;
let statPeriod='week';
let draft=newDraft();
const content=document.getElementById('content');
const modal=document.getElementById('modal');
const modalBody=document.getElementById('modal-body');
const wizardActions=document.getElementById('wizard-actions');

function newDraft(){return {situation:'',situationDetail:'',body:[],regions:[],valence:'',energy:'',arousal:'',impulses:[],subs:[],relationStarter:'Ich fühle mich so, weil …',relation:'',thought:'',intensity:5,candidates:[],chosenMain:'',confidence:50,needs:[],needCustom:'',createdAt:new Date().toISOString()}}
function loadJson(k,f){try{return JSON.parse(localStorage.getItem(k))||f}catch{return f}}
function saveCatalog(){localStorage.setItem(STORAGE,JSON.stringify(catalog))}
function saveEntries(){localStorage.setItem(ENTRIES,JSON.stringify(entries))}
function esc(v=''){return String(v).replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]))}
function toast(msg){const t=document.getElementById('toast');t.textContent=msg;t.classList.remove('hidden');setTimeout(()=>t.classList.add('hidden'),2600)}
function colorOf(name){return catalog.main.find(x=>x.name===name)?.color||'#789c95'}
function chipSize(label){return label.length>19?'.74rem':label.length>14?'.82rem':label.length>10?'.9rem':'1rem'}
function setPage(p){page=p;content.classList.add('dialog-mode');wizardActions.classList.remove('hidden');document.querySelectorAll('.nav').forEach(b=>b.classList.toggle('active',b.dataset.page===p));content.classList.toggle('dialog-mode',p==='dialog');wizardActions.classList.toggle('hidden',p!=='dialog');render()}
function toggle(arr,value){const i=arr.indexOf(value);i>=0?arr.splice(i,1):arr.push(value)}
function addUnique(list,value){const v=value.trim();if(v&&!list.some(x=>(typeof x==='string'?x:x.name).toLowerCase()===v.toLowerCase()))list.push(v);return v}

function render(){if(page==='dialog')renderDialog();if(page==='history')renderHistory();if(page==='stats')renderStats();if(page==='catalog')renderCatalog()}
function shell(title,intro,body){content.innerHTML=`<section class="panel"><h1 class="screen-title">${title}</h1>${intro?`<p class="intro">${intro}</p>`:''}${body}</section>`}
function stepShell(title,intro,body,canNext=true){
  content.classList.add('dialog-mode');
  wizardActions.classList.add('hidden');
  const actions=`<div class="dialog-actions" aria-label="Dialognavigation">${step>1?'<button type="button" class="ghost" id="back">Zurück</button>':''}<button type="button" class="primary" id="next" data-ready="${canNext}">${step===10?'Zusammenfassung':'Weiter'}</button></div>`;
  content.innerHTML=`<section class="panel dialog-panel"><div class="step-head"><div><div class="eyebrow">Schritt ${step} von 10</div><h1>${title}</h1><p class="muted">${intro}</p></div></div><div class="progress"><div style="width:${step*10}%"></div></div>${body}${actions}</section>`;
  document.getElementById('back')?.addEventListener('click',()=>{step--;renderDialog();window.scrollTo({top:0,behavior:'smooth'})});
  document.getElementById('next')?.addEventListener('click',()=>{if(validateStep()){step++;if(step===8)deriveMain();if(step===11)return renderSummary();renderDialog();window.scrollTo({top:0,behavior:'smooth'})}})
}
function validateStep(){if(step===1&&!draft.situation){toast('Bitte wähle einen Kontext.');return false}if(step===2&&!draft.body.length){toast('Bitte wähle mindestens eine Körperempfindung.');return false}if(step===3&&(!draft.valence||!draft.energy||!draft.arousal)){toast('Bitte beantworte die drei Grundfragen.');return false}if(step===5&&!draft.subs.length){toast('Bitte wähle mindestens ein mögliches Untergefühl.');return false}if(step===8&&!draft.chosenMain&&draft.candidates.length){toast('Bitte wähle das am besten passende Hauptgefühl.');return false}return true}

function renderDialog(){if(step>10){renderSummary();return}if(step===1)renderSituation();if(step===2)renderBody();if(step===3)renderDirection();if(step===4)renderImpulse();if(step===5)renderSubfeelings();if(step===6)renderRelation();if(step===7)renderIntensity();if(step===8)renderMain();if(step===9)renderConfidence();if(step===10)renderNeeds()}
function renderSituation(){const cards=catalog.situations.map((s,i)=>`<button class="choice ${draft.situation===s.name?'selected':''}" data-i="${i}"><strong>${esc(s.name)}</strong><small>${esc(s.hint||'')}</small></button>`).join('');stepShell('In welchem Kontext bist du gerade?','Die Auswahl beschreibt den groben Rahmen, nicht zwingend nur einen Ort.',`<div class="choice-grid" id="situations">${cards}</div>${draft.situation==='Sonstiges'?`<label class="field"><span>Eigener Kontext</span><input id="other-situation" value="${esc(draft.situationDetail)}" placeholder="z. B. Behördentermin"></label>`:''}<label class="field"><span>Was geschieht gerade? (optional)</span><textarea id="event-text" placeholder="Nur möglichst nüchtern beschreiben, noch ohne Bewertung.">${esc(draft.eventText||'')}</textarea></label>`,!!draft.situation);document.querySelectorAll('#situations .choice').forEach(b=>b.onclick=()=>{draft.situation=catalog.situations[+b.dataset.i].name;draft.situationDetail='';renderSituation()});document.getElementById('other-situation')?.addEventListener('input',e=>draft.situationDetail=e.target.value);document.getElementById('event-text').addEventListener('input',e=>draft.eventText=e.target.value);document.getElementById('next').onclick=()=>{if(draft.situation==='Sonstiges'&&draft.situationDetail.trim()){const custom=draft.situationDetail.trim();if(!catalog.situations.some(s=>s.name.toLowerCase()===custom.toLowerCase())){catalog.situations.splice(catalog.situations.length-1,0,{name:custom,hint:'Eigener Kontext'});saveCatalog()}draft.situation=custom}if(validateStep()){step++;renderDialog()}}}
function renderBody(){stepShell('Was spürst du im Körper?','Wähle zunächst nur, was du wahrnimmst. Die Bedeutung kommt später.',`<h3>Körperempfindungen</h3><div class="chip-cloud" id="body">${catalog.body.map(x=>chip(x,draft.body.includes(x))).join('')}</div><h3>Wo spürst du es?</h3><div class="chip-cloud" id="regions">${catalog.regions.map(x=>chip(x,draft.regions.includes(x))).join('')}</div>`,draft.body.length>0);bindChips('body',draft.body);bindChips('regions',draft.regions)}
function renderDirection(){stepShell('Wie ist die grobe Richtung?','Du musst noch kein exaktes Gefühlswort kennen.',`${mirror()}${choiceQuestion('Wie fühlt sich der Zustand an?',['angenehm','neutral','unangenehm'],'valence')}${choiceQuestion('Wie viel Energie hast du?',['wenig','mittel','viel'],'energy')}${choiceQuestion('Wie wirkt dein Körper?',['ruhig','angespannt','aufgewühlt'],'arousal')}`,!!draft.valence&&!!draft.energy&&!!draft.arousal);bindChoices()}
function renderImpulse(){stepShell('Was möchtest du gerade am liebsten tun?','Der Handlungsimpuls kann ein guter Spürhund sein. Mehrfachauswahl ist möglich.',`${mirror()}<div class="chip-cloud" id="impulses">${catalog.impulses.map(x=>chip(x,draft.impulses.includes(x))).join('')}</div>`,true);bindChips('impulses',draft.impulses)}
function renderSubfeelings(){const suggestions=suggestSubs();const list=showAllSubs?catalog.sub:suggestions;stepShell('Welche Wörter könnten passen?','Die Vorschläge sind eine Hilfe, keine Diagnose. Mehrere Wörter dürfen gleichzeitig passen.',`${mirror()}${suggestions.length?'<h3>Das könnte passen</h3>':'<p class="status open">Aus den bisherigen Angaben ergibt sich noch kein klarer Vorschlag. Das ist völlig in Ordnung.</p>'}<div class="chip-cloud" id="subs">${list.map(x=>chip(x.name,draft.subs.includes(x.name),colorOf(x.main))).join('')}</div><button class="ghost" id="toggle-all">${showAllSubs?'Nur Vorschläge zeigen':'Alle Untergefühle anzeigen'}</button>`,draft.subs.length>0);bindChips('subs',draft.subs);document.getElementById('toggle-all').onclick=()=>{showAllSubs=!showAllSubs;renderSubfeelings()}}
function renderRelation(){const starters=['Ich fühle mich so, weil …','Das hängt zusammen mit …','Ich denke gerade …','Das erinnert mich an …','Ich wünsche mir …'];stepShell('Womit hängt das zusammen?','Gefühl plus Bezug ist oft hilfreicher als ein einzelnes Wort.',`${mirror()}<div class="sentence-starters">${starters.map(s=>`<button class="starter" data-v="${esc(s)}">${esc(s)}</button>`).join('')}</div><label class="field"><span>${esc(draft.relationStarter)}</span><textarea id="relation" placeholder="Deine Erklärung oder Bedeutung …">${esc(draft.relation)}</textarea></label><label class="field"><span>Was ging dir durch den Kopf? (optional)</span><textarea id="thought" placeholder="z. B. Ich müsste eigentlich produktiver sein.">${esc(draft.thought)}</textarea></label>`,true);document.querySelectorAll('.starter').forEach(b=>b.onclick=e=>{e.preventDefault();draft.relationStarter=b.dataset.v;renderRelation()});document.getElementById('relation').oninput=e=>draft.relation=e.target.value;document.getElementById('thought').oninput=e=>draft.thought=e.target.value}
function renderIntensity(){stepShell('Wie stark ist die Empfindung?','Nicht das perfekte Maß suchen, sondern eine brauchbare Momentaufnahme.',`${mirror()}<div class="scale"><input id="intensity" type="range" min="0" max="10" step="1" value="${draft.intensity}"><span class="score" id="intensity-value">${draft.intensity}/10</span></div>`,true);document.getElementById('intensity').oninput=e=>{draft.intensity=+e.target.value;document.getElementById('intensity-value').textContent=`${draft.intensity}/10`}}
function renderMain(){deriveMain();const status=draft.candidates.length>1?'Aus deinen Wörtern ergeben sich mehrere Gefühlsbereiche. Das ist eine wertvolle Beobachtung.':draft.candidates.length===1?'Die gewählten Untergefühle weisen in eine gemeinsame Richtung.':'Noch kein Hauptgefühl ableitbar.';const candidateCards=draft.candidates.map(m=>emotionCard(m,true)).join('');const otherMains=catalog.main.filter(m=>!draft.candidates.includes(m.name));const allCards=showAllMainFeelings?`<div class="all-main-wrap"><h3>Alle Hauptgefühle</h3><div class="derived">${otherMains.map(m=>emotionCard(m.name,false)).join('')}</div></div>`:'';stepShell('Welches Hauptgefühl passt am ehesten?',status,`${mirror()}${candidateCards?`<h3>Aus deinen Untergefühlen abgeleitet</h3><div class="derived">${candidateCards}</div>`:'<p class="status open">Du kannst „noch nicht bestimmt“ speichern oder ein anderes Hauptgefühl wählen.</p>'}<button class="ghost main-toggle" id="toggle-main">${showAllMainFeelings?'Andere Hauptgefühle ausblenden':'Anderes Hauptgefühl wählen'}</button>${allCards}`,draft.candidates.length===0||!!draft.chosenMain);document.querySelectorAll('.emotion-card').forEach(b=>b.addEventListener('click',e=>{e.preventDefault();draft.chosenMain=b.dataset.m;renderMain()}));document.getElementById('toggle-main').onclick=()=>{showAllMainFeelings=!showAllMainFeelings;renderMain()}}
function emotionCard(name,derived){const subs=derived?draft.subs.filter(s=>catalog.sub.find(x=>x.name===s)?.main===name).join(', '):'Manuell gewählt';return `<button type="button" class="emotion-card ${draft.chosenMain===name?'selected':''}" data-m="${esc(name)}" style="border-color:${colorOf(name)}"><strong>${esc(name)}</strong><small>${esc(subs)}</small></button>`}
function renderConfidence(){const feelingSummary=draft.chosenMain||draft.candidates.join(' oder ')||'noch nicht bestimmt';stepShell('Wie gut passt diese Benennung?',`Es ist völlig in Ordnung, unsicher zu sein. Genau diese Entwicklung soll später sichtbar werden.`,`${mirror()}<div class="feeling-reminder"><span>Bisheriges Hauptgefühl</span><strong>${esc(feelingSummary)}</strong>${draft.candidates.length>1?`<small>Ursprünglich möglich: ${esc(draft.candidates.join(', '))}</small>`:''}</div><div class="scale"><input id="confidence" type="range" min="0" max="100" step="5" value="${draft.confidence}"><span class="score" id="confidence-value">${draft.confidence}%</span></div><p class="muted">0 % = sehr unsicher · 100 % = passt sehr gut</p>`,true);document.getElementById('confidence').oninput=e=>{draft.confidence=+e.target.value;document.getElementById('confidence-value').textContent=`${draft.confidence}%`}}
function renderNeeds(){stepShell('Was brauchst du jetzt?','Diese Frage ist optional. Eigene Bedürfnisse werden automatisch in den Katalog aufgenommen.',`<div class="chip-cloud" id="needs">${catalog.needs.map(x=>chip(x,draft.needs.includes(x))).join('')}</div><label class="field"><span>Eigenes Bedürfnis</span><input id="need-custom" value="${esc(draft.needCustom)}" placeholder="z. B. frische Luft"></label>`,true);bindChips('needs',draft.needs);document.getElementById('need-custom').oninput=e=>draft.needCustom=e.target.value;document.getElementById('next').onclick=()=>{const v=draft.needCustom.trim();if(v){if(!catalog.needs.some(x=>x.toLowerCase()===v.toLowerCase())){catalog.needs.push(v);saveCatalog()}if(!draft.needs.includes(v))draft.needs.push(v)}step=11;renderSummary()}}
function renderSummary(){wizardActions.classList.add('hidden');content.classList.remove('dialog-mode');deriveMain();const ambiguity=draft.candidates.length>1?'mehrdeutig':draft.candidates.length===1?'eindeutig':'offen';content.innerHTML=`<section class="panel"><div class="eyebrow">Zusammenfassung</div><h1>Dein Gefühls-Kompass</h1><p class="muted">Das Ergebnis muss nicht perfekt sein. Wichtig ist, dass du deinen Zustand Schritt für Schritt erkundet hast.</p><div class="status ${ambiguity==='mehrdeutig'?'ambiguous':ambiguity==='offen'?'open':''}"><strong>${ambiguity==='mehrdeutig'?'Mehrere Gefühle waren zunächst möglich.':ambiguity==='eindeutig'?'Die Ableitung war in diesem Eintrag eindeutig.':'Das Hauptgefühl ist noch nicht bestimmt.'}</strong></div><dl class="summary-grid"><dt>Kontext</dt><dd>${esc(draft.situation)}</dd><dt>Körper</dt><dd>${esc(draft.body.join(', '))}${draft.regions.length?` · ${esc(draft.regions.join(', '))}`:''}</dd><dt>Grundrichtung</dt><dd>${esc([draft.valence,draft.energy+' Energie',draft.arousal].join(' · '))}</dd><dt>Handlungsimpuls</dt><dd>${esc(draft.impulses.join(', ')||'nicht angegeben')}</dd><dt>Untergefühle</dt><dd>${esc(draft.subs.join(', '))}</dd><dt>Abgeleitete Gefühle</dt><dd>${esc(draft.candidates.join(', ')||'noch offen')}</dd><dt>Gewähltes Gefühl</dt><dd><strong>${esc(draft.chosenMain||'noch nicht bestimmt')}</strong></dd><dt>Intensität</dt><dd>${draft.intensity}/10</dd><dt>Sicherheit</dt><dd>${draft.confidence}%</dd><dt>Bedürfnis</dt><dd>${esc(draft.needs.join(', ')||'nicht angegeben')}</dd></dl><div class="button-row"><button class="ghost" id="summary-back">Zurück</button><button type="button" class="primary" id="save-demo">Speichern & neuer Eintrag</button></div></section>`;document.getElementById('summary-back').onclick=()=>{step=10;renderDialog()};document.getElementById('save-demo').onclick=()=>{entries.unshift({...structuredClone(draft),ambiguity,id:Date.now()});saveEntries();toast('Prototyp-Eintrag gespeichert.');draft=newDraft();step=1;showAllSubs=false;showAllMainFeelings=false;setPage('dialog')}}

function mirror(){return `<div class="mirror"><strong>Bisher:</strong> ${esc(draft.situation||'–')}${draft.body.length?` · ${esc(draft.body.join(', '))}`:''}${draft.subs.length?` · ${esc(draft.subs.join(', '))}`:''}</div>`}
function choiceQuestion(q,options,key){return `<h3>${q}</h3><div class="choice-grid" data-key="${key}">${options.map(o=>`<button class="choice ${draft[key]===o?'selected':''}" data-v="${o}"><strong>${o}</strong></button>`).join('')}</div>`}
function bindChoices(){document.querySelectorAll('.choice-grid[data-key] .choice').forEach(b=>b.onclick=()=>{draft[b.parentElement.dataset.key]=b.dataset.v;renderDirection()})}
function chip(label,selected,color){return `<button class="chip ${selected?'selected':''}" data-v="${esc(label)}" style="--chip-size:${chipSize(label)};${color?`--chip-bg:${color}35;${selected?`background:${color};`:''}`:''}">${esc(label)}</button>`}
function bindChips(id,array){document.querySelectorAll(`#${id} .chip`).forEach(b=>b.onclick=e=>{e.preventDefault();toggle(array,b.dataset.v);b.classList.toggle('selected')})}
function suggestSubs(){return catalog.sub.map(x=>{let score=0;score+=x.body.filter(v=>draft.body.includes(v)).length*3;if(x.valence===draft.valence)score+=2;if(x.energy===draft.energy)score++;if(x.arousal===draft.arousal)score+=2;score+=x.impulses.filter(v=>draft.impulses.includes(v)).length*2;return {x,score}}).filter(v=>v.score>=3).sort((a,b)=>b.score-a.score).slice(0,8).map(v=>v.x)}
function deriveMain(){draft.candidates=[...new Set(draft.subs.map(s=>catalog.sub.find(x=>x.name===s)?.main).filter(Boolean))];if(draft.candidates.length===1)draft.chosenMain=draft.candidates[0];else if(!draft.candidates.includes(draft.chosenMain))draft.chosenMain=''}

function renderHistory(){wizardActions.classList.add('hidden');content.classList.remove('dialog-mode');shell('Verlauf','Im Klick-Prototyp werden Testeinträge nur lokal im Browser gespeichert.',entries.length?entries.map(e=>`<article class="panel history-card"><div class="step-head"><div><div class="eyebrow">${new Date(e.createdAt).toLocaleString('de-DE')}</div><h2>${esc(e.chosenMain||'Noch nicht bestimmt')}</h2></div><span class="status ${e.ambiguity==='mehrdeutig'?'ambiguous':''}">${esc(e.ambiguity)}</span></div><p>${esc(e.situation)} · ${esc(e.body.join(', '))}</p><p><strong>${esc(e.subs.join(', '))}</strong></p><p class="muted">Sicherheit ${e.confidence}% · Intensität ${e.intensity}/10</p></article>`).join(''):'<div class="empty">Noch keine Prototyp-Einträge gespeichert.</div>')}
function renderStats(){wizardActions.classList.add('hidden');content.classList.remove('dialog-mode');const source=entries.length?entries:demoEntries();const filtered=filterPeriod(source,statPeriod);const counts={};filtered.forEach(e=>counts[e.chosenMain||'Offen']=(counts[e.chosenMain||'Offen']||0)+1);const total=Math.max(1,filtered.length);let angle=0;const segments=Object.entries(counts).map(([name,n])=>{const start=angle;angle+=n/total*360;return `${colorOf(name)} ${start}deg ${angle}deg`}).join(',');const ambiguous=filtered.filter(e=>e.ambiguity==='mehrdeutig').length;const avg=Math.round(filtered.reduce((a,e)=>a+(e.confidence||0),0)/total);shell('Auswertungen','Beispieldaten zeigen, wie die spätere Statistik aussehen könnte.',`<div class="tabs"><button data-period="week" class="${statPeriod==='week'?'active':''}">Woche</button><button data-period="month" class="${statPeriod==='month'?'active':''}">Monat</button></div><div class="stats-grid"><section class="panel chart-box"><h2>Gefühlsverteilung</h2><div class="pie-wrap"><div class="pie" style="background:conic-gradient(${segments||'#ddd 0 360deg'})"></div></div><div class="legend">${Object.entries(counts).map(([n,c])=>`<div class="legend-row"><span class="dot" style="background:${colorOf(n)}"></span><span>${esc(n)}</span><strong>${c}</strong></div>`).join('')}</div></section><section class="panel chart-box"><h2>Lernfortschritt</h2><p><strong>${avg}%</strong> durchschnittliche Sicherheit</p><div class="bar-track"><div class="bar" style="width:${avg}%"></div></div><p><strong>${ambiguous}</strong> von ${filtered.length} Einträgen waren zunächst mehrdeutig.</p><h3>Mehrdeutigkeit ist kein Fehler</h3><p class="muted">Sie zeigt, bei welchen Gefühlsbereichen sich die Unterscheidung noch entwickelt.</p></section></div>`);document.querySelectorAll('[data-period]').forEach(b=>b.onclick=()=>{statPeriod=b.dataset.period;renderStats()})}
function demoEntries(){const now=Date.now();return [
 {createdAt:new Date(now-1*86400000).toISOString(),chosenMain:'Trauer',confidence:45,ambiguity:'mehrdeutig'},
 {createdAt:new Date(now-2*86400000).toISOString(),chosenMain:'Angst',confidence:60,ambiguity:'eindeutig'},
 {createdAt:new Date(now-4*86400000).toISOString(),chosenMain:'Freude',confidence:72,ambiguity:'eindeutig'},
 {createdAt:new Date(now-9*86400000).toISOString(),chosenMain:'Scham',confidence:50,ambiguity:'mehrdeutig'},
 {createdAt:new Date(now-13*86400000).toISOString(),chosenMain:'Ärger',confidence:68,ambiguity:'eindeutig'},
 {createdAt:new Date(now-18*86400000).toISOString(),chosenMain:'Freude',confidence:80,ambiguity:'eindeutig'}]}
function filterPeriod(data,p){const days=p==='week'?7:31;const min=Date.now()-days*86400000;return data.filter(e=>new Date(e.createdAt).getTime()>=min)}

function renderCatalog(){wizardActions.classList.add('hidden');content.classList.remove('dialog-mode');shell('Katalog','Alle Auswahllisten des Prototyps lassen sich hier verändern. Körperregionen und Handlungsimpulse werden bewusst nur hier gepflegt.',`${catalogBlock('Situationen','situations',catalog.situations.map(x=>x.name))}${catalogBlock('Körperempfindungen','body',catalog.body)}${catalogBlock('Körperregionen','regions',catalog.regions)}${catalogBlock('Handlungsimpulse','impulses',catalog.impulses)}${catalogBlock('Bedürfnisse','needs',catalog.needs)}${subCatalog()}<div class="button-row"><button class="danger" id="reset-catalog">Prototyp-Katalog zurücksetzen</button></div>`);bindCatalog();document.getElementById('reset-catalog').onclick=()=>openConfirm('Katalog zurücksetzen?','Alle Änderungen des Klick-Prototyps werden verworfen.',()=>{catalog=structuredClone(defaults);saveCatalog();renderCatalog();toast('Katalog zurückgesetzt.')})}
function catalogBlock(title,key,items){return `<section class="catalog-section"><h2>${title}</h2><div class="catalog-list">${items.map((x,i)=>`<div class="catalog-item"><span>${esc(x)}</span><button data-remove="${key}" data-i="${i}">Entfernen</button></div>`).join('')}</div><div class="button-row"><button class="secondary" data-add="${key}">+ ${title.slice(0,-1)||title}</button></div></section>`}
function subCatalog(){return `<section class="catalog-section"><h2>Untergefühle</h2><div class="catalog-list">${catalog.sub.map((x,i)=>`<div class="catalog-item"><span><strong>${esc(x.name)}</strong> → ${esc(x.main)}</span><button data-remove="sub" data-i="${i}">Entfernen</button></div>`).join('')}</div><div class="button-row"><button class="secondary" data-add="sub">+ Untergefühl</button></div></section>`}
function bindCatalog(){document.querySelectorAll('[data-remove]').forEach(b=>b.onclick=()=>{const k=b.dataset.remove,i=+b.dataset.i;if(k==='situations')catalog.situations.splice(i,1);else catalog[k].splice(i,1);saveCatalog();renderCatalog()});document.querySelectorAll('[data-add]').forEach(b=>b.onclick=()=>openAdd(b.dataset.add))}
function openAdd(key){if(key==='sub'){modalBody.innerHTML=`<h2>Untergefühl hinzufügen</h2><label class="field"><span>Untergefühl</span><input id="m-name"></label><label class="field"><span>Hauptgefühl</span><select id="m-main">${catalog.main.map(x=>`<option>${esc(x.name)}</option>`).join('')}</select></label><p class="muted">Im funktionalen Prototyp können zusätzlich Vorschlagsregeln zu Körper, Grundrichtung und Handlungsimpuls gepflegt werden.</p><div class="button-row"><button value="cancel" class="ghost">Abbrechen</button><button value="default" class="primary" id="m-save">Speichern</button></div>`;modal.showModal();document.getElementById('m-save').onclick=e=>{e.preventDefault();const n=document.getElementById('m-name').value.trim(),m=document.getElementById('m-main').value;if(n){catalog.sub.push({name:n,main:m,body:[],valence:'',energy:'',arousal:'',impulses:[]});saveCatalog();modal.close();renderCatalog()}};return}modalBody.innerHTML=`<h2>Eintrag hinzufügen</h2><label class="field"><span>Bezeichnung</span><input id="m-name"></label>${key==='situations'?'<label class="field"><span>Kurze Erläuterung</span><input id="m-hint"></label>':''}<div class="button-row"><button value="cancel" class="ghost">Abbrechen</button><button value="default" class="primary" id="m-save">Speichern</button></div>`;modal.showModal();document.getElementById('m-save').onclick=e=>{e.preventDefault();const n=document.getElementById('m-name').value.trim();if(!n)return;if(key==='situations')catalog.situations.splice(Math.max(0,catalog.situations.length-1),0,{name:n,hint:document.getElementById('m-hint').value.trim()||'Eigener Kontext'});else addUnique(catalog[key],n);saveCatalog();modal.close();renderCatalog()}}
function openConfirm(title,text,yes){modalBody.innerHTML=`<h2>${esc(title)}</h2><p>${esc(text)}</p><div class="button-row"><button value="cancel" class="ghost">Abbrechen</button><button value="default" class="danger" id="confirm-yes">Bestätigen</button></div>`;modal.showModal();document.getElementById('confirm-yes').onclick=e=>{e.preventDefault();modal.close();yes()}}

document.querySelectorAll('.nav').forEach(b=>b.onclick=()=>setPage(b.dataset.page));document.getElementById('restart').onclick=()=>openConfirm('Dialog neu starten?','Die bisherigen Angaben dieses Durchgangs werden verworfen.',()=>{draft=newDraft();step=1;showAllSubs=false;showAllMainFeelings=false;setPage('dialog')});
if('serviceWorker' in navigator){
  window.addEventListener('load',async()=>{
    try{
      const registration=await navigator.serviceWorker.register('./sw.js?v=0.8',{updateViaCache:'none'});
      await registration.update();
    }catch(error){console.warn('Service Worker konnte nicht aktualisiert werden.',error)}
  });
}
render();
