const VERSION='0.21';
const DB_NAME='gefuehlskompass-phase2-db';
const DB_VERSION=1;

const defaults={
  situations:[
    {name:'Zuhause',hint:'Wohnung, Haus oder eigener Rückzugsort'},
    {name:'Arbeit',hint:'Arbeitsplatz, Besprechung oder berufliche Aufgabe'},
    {name:'Unterwegs',hint:'S-Bahn, Auto, zu Fuß oder beim Einkauf'},
    {name:'Familie',hint:'Kontakt oder Situation mit Familie'},
    {name:'Freunde',hint:'Kontakt oder Situation mit Freund:innen'},
    {name:'Freizeit',hint:'Hobby, Medien, Sport oder Erholung'},
    {name:'Gesundheit / Behandlung',hint:'Arzttermin, Therapie, Beschwerden, Medikamente oder Pflege'},
    {name:'Sonstiges',hint:'Anderen Kontext selbst eingeben'}
  ],
  body:['Schmerz','Druck','Schwere','Wärme','Kälte','Müdigkeit','Hunger','Durst','Unruhe','Anspannung','Entspannung','Leichtigkeit','Kribbeln'],
  regions:['Kopf','Kiefer','Nacken','Schultern','Brust','Bauch','Rücken','Arme','Hände','Beine','ganzer Körper'],
  impulses:['Bleiben','Weggehen','Schlafen','Mich verstecken','Reden','Allein sein','Nähe suchen','Weinen','Etwas verändern','Widersprechen','Bewegen','Nichts tun'],
  needs:['Ruhe','Sicherheit','Nähe','Abstand','Bewegung','Essen','Schlaf','Struktur','Unterstützung','Verständnis','Ablenkung','Zeit für mich'],
  main:[
    {name:'Freude',color:'#77a982'},
    {name:'Angst',color:'#c77b77'},
    {name:'Scham',color:'#c89aaa'},
    {name:'Ekel',color:'#d69c67'},
    {name:'Trauer',color:'#9383ad'},
    {name:'Ärger',color:'#789eb5'},
    {name:'Schuld',color:'#cfbd66'}
  ],
  sub:[
    {name:'zufrieden',main:'Freude',body:['Leichtigkeit','Wärme','Entspannung'],valence:['angenehm'],energy:['mittel','wenig'],arousal:['ruhig'],impulses:['Bleiben']},
    {name:'geborgen',main:'Freude',body:['Wärme','Leichtigkeit','Entspannung'],valence:['angenehm'],energy:['wenig','mittel'],arousal:['ruhig'],impulses:['Nähe suchen','Bleiben']},
    {name:'interessiert',main:'Freude',body:['Kribbeln','Leichtigkeit'],valence:['angenehm','neutral'],energy:['mittel','viel'],arousal:['ruhig','aufgewühlt'],impulses:['Bleiben','Bewegen']},
    {name:'angespannt',main:'Angst',body:['Anspannung','Druck','Schmerz'],valence:['unangenehm'],energy:['mittel','viel'],arousal:['angespannt','aufgewühlt'],impulses:['Weggehen','Etwas verändern']},
    {name:'unsicher',main:'Angst',body:['Unruhe','Druck','Kribbeln'],valence:['unangenehm','neutral'],energy:['mittel'],arousal:['aufgewühlt','angespannt'],impulses:['Mich verstecken','Nähe suchen']},
    {name:'überfordert',main:'Angst',body:['Schmerz','Druck','Schwere','Müdigkeit'],valence:['unangenehm'],energy:['wenig','mittel'],arousal:['aufgewühlt','angespannt'],impulses:['Weggehen','Allein sein']},
    {name:'gereizt',main:'Ärger',body:['Anspannung','Schmerz','Wärme'],valence:['unangenehm'],energy:['mittel','viel'],arousal:['angespannt','aufgewühlt'],impulses:['Widersprechen','Etwas verändern']},
    {name:'frustriert',main:'Ärger',body:['Druck','Anspannung','Schwere'],valence:['unangenehm'],energy:['mittel'],arousal:['angespannt'],impulses:['Etwas verändern','Widersprechen']},
    {name:'bedrückt',main:'Trauer',body:['Schwere','Müdigkeit','Druck'],valence:['unangenehm'],energy:['wenig'],arousal:['ruhig','angespannt'],impulses:['Weinen','Allein sein']},
    {name:'traurig',main:'Trauer',body:['Schwere','Müdigkeit'],valence:['unangenehm'],energy:['wenig'],arousal:['ruhig'],impulses:['Weinen','Nähe suchen']},
    {name:'unglücklich',main:'Trauer',body:['Schwere','Müdigkeit','Druck'],valence:['unangenehm'],energy:['wenig','mittel'],arousal:['ruhig','angespannt'],impulses:['Allein sein','Nähe suchen']},
    {name:'peinlich berührt',main:'Scham',body:['Wärme','Anspannung','Kribbeln'],valence:['unangenehm'],energy:['mittel'],arousal:['aufgewühlt','angespannt'],impulses:['Mich verstecken','Weggehen']},
    {name:'beschämt',main:'Scham',body:['Wärme','Schwere','Anspannung'],valence:['unangenehm'],energy:['wenig','mittel'],arousal:['angespannt'],impulses:['Mich verstecken']},
    {name:'schuldig',main:'Schuld',body:['Druck','Schwere'],valence:['unangenehm'],energy:['wenig','mittel'],arousal:['angespannt'],impulses:['Etwas verändern','Reden']},
    {name:'angewidert',main:'Ekel',body:['Unruhe','Kälte','Anspannung'],valence:['unangenehm'],energy:['mittel'],arousal:['angespannt'],impulses:['Weggehen']}
  ]
};

let db;
let catalog;
let entries=[];
let page='dialog';
let step=1;
let showAllSubs=false;
let showAllMain=false;
let editingId=null;
let draft=newDraft();

const content=document.getElementById('content');
const modal=document.getElementById('modal');
const modalBody=document.getElementById('modal-body');
const catalogFile=document.getElementById('catalog-file');
const dataFile=document.getElementById('data-file');

function newDraft(){return {id:null,situation:'',situationDetail:'',eventText:'',body:[],regions:[],valence:'',energy:'',arousal:'',impulses:[],subs:[],relationStarter:'Ich fühle mich so, weil …',relation:'',thought:'',intensity:5,candidates:[],chosenMain:'',confidence:50,needs:[],needCustom:'',feelingMessage:'',createdAt:new Date().toISOString()}}
function clone(v){return JSON.parse(JSON.stringify(v))}
function esc(v=''){return String(v).replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]))}
function toast(msg){const t=document.getElementById('toast');t.textContent=msg;t.classList.remove('hidden');setTimeout(()=>t.classList.add('hidden'),2800)}
function colorOf(name){return catalog.main.find(x=>x.name===name)?.color||'#789c95'}
function chipSize(label){return label.length>19?'.74rem':label.length>14?'.82rem':label.length>10?'.9rem':'1rem'}
function toggle(arr,value){const i=arr.indexOf(value);i>=0?arr.splice(i,1):arr.push(value)}
function addUnique(list,value){const v=value.trim();if(v&&!list.some(x=>(typeof x==='string'?x:x.name).toLowerCase()===v.toLowerCase()))list.push(v);return v}
function chip(label,selected,color=''){return `<button type="button" class="chip ${selected?'selected':''}" data-v="${esc(label)}" style="--chip-size:${chipSize(label)};${color?`--chip-bg:${color}35;${selected?`background:${color};`:''}`:''}">${esc(label)}</button>`}
function bindChips(id,array,rerender=null){document.querySelectorAll(`#${id} .chip`).forEach(b=>b.onclick=e=>{e.preventDefault();toggle(array,b.dataset.v);if(rerender)rerender();else b.classList.toggle('selected')})}

function openDb(){return new Promise((resolve,reject)=>{const req=indexedDB.open(DB_NAME,DB_VERSION);req.onupgradeneeded=()=>{const d=req.result;if(!d.objectStoreNames.contains('meta'))d.createObjectStore('meta');if(!d.objectStoreNames.contains('entries'))d.createObjectStore('entries',{keyPath:'id'})};req.onsuccess=()=>resolve(req.result);req.onerror=()=>reject(req.error)})}
function idbGet(store,key){return new Promise((resolve,reject)=>{const tx=db.transaction(store,'readonly');const req=tx.objectStore(store).get(key);req.onsuccess=()=>resolve(req.result);req.onerror=()=>reject(req.error)})}
function idbPut(store,value,key){return new Promise((resolve,reject)=>{const tx=db.transaction(store,'readwrite');const req=key===undefined?tx.objectStore(store).put(value):tx.objectStore(store).put(value,key);req.onsuccess=()=>resolve();req.onerror=()=>reject(req.error)})}
function idbDelete(store,key){return new Promise((resolve,reject)=>{const tx=db.transaction(store,'readwrite');const req=tx.objectStore(store).delete(key);req.onsuccess=()=>resolve();req.onerror=()=>reject(req.error)})}
function idbAll(store){return new Promise((resolve,reject)=>{const tx=db.transaction(store,'readonly');const req=tx.objectStore(store).getAll();req.onsuccess=()=>resolve(req.result||[]);req.onerror=()=>reject(req.error)})}
async function saveCatalog(){await idbPut('meta',catalog,'catalog')}
async function saveEntry(entry){await idbPut('entries',entry);entries=await idbAll('entries');entries.sort((a,b)=>new Date(b.createdAt)-new Date(a.createdAt))}

function setPage(p){page=p;document.querySelectorAll('.nav').forEach(b=>b.classList.toggle('active',b.dataset.page===p));render()}
function render(){if(page==='dialog')renderDialog();if(page==='history')renderHistory();if(page==='stats')renderStats();if(page==='catalog')renderCatalog()}
function shell(title,intro,body){content.innerHTML=`<section class="panel"><h1 class="screen-title">${title}</h1>${intro?`<p class="intro">${intro}</p>`:''}${body}</section>`}
function stepShell(title,intro,body){const actions=`<div class="dialog-actions">${step>1?'<button type="button" class="ghost" id="back">Zurück</button>':''}<button type="button" class="primary" id="next">${step===10?'Zusammenfassung':'Weiter'}</button></div>`;content.innerHTML=`<section class="panel dialog-panel"><div class="eyebrow">Schritt ${step} von 10</div><h1>${title}</h1><p class="muted">${intro}</p><div class="progress"><div style="width:${step*10}%"></div></div>${body}${actions}</section>`;document.getElementById('back')?.addEventListener('click',()=>{step--;renderDialog();window.scrollTo(0,0)});document.getElementById('next').addEventListener('click',()=>{if(validateStep()){step++;if(step===8)deriveMain();renderDialog();window.scrollTo(0,0)}})}
function validateStep(){if(step===1&&!draft.situation){toast('Bitte wähle einen Kontext.');return false}if(step===2&&!draft.body.length){toast('Bitte wähle mindestens eine Körperempfindung.');return false}if(step===3&&(!draft.valence||!draft.energy||!draft.arousal)){toast('Bitte beantworte die drei Grundfragen.');return false}if(step===5&&!draft.subs.length){toast('Bitte wähle mindestens ein mögliches Untergefühl.');return false}if(step===8&&!draft.chosenMain&&draft.candidates.length){toast('Bitte wähle das am besten passende Hauptgefühl.');return false}return true}

function renderDialog(){if(step===11)return renderSummary();({1:renderSituation,2:renderBody,3:renderDirection,4:renderImpulse,5:renderSubfeelings,6:renderRelation,7:renderIntensity,8:renderMain,9:renderConfidence,10:renderNeeds}[step])()}
function renderSituation(){const cards=catalog.situations.map((s,i)=>`<button type="button" class="choice ${draft.situation===s.name?'selected':''}" data-i="${i}"><strong>${esc(s.name)}</strong><small>${esc(s.hint||'')}</small></button>`).join('');stepShell('In welchem Kontext bist du gerade?','Beschreibe zuerst den groben Rahmen. Das konkrete Geschehen kannst du darunter nüchtern notieren.',`<div class="choice-grid" id="situations">${cards}</div>${draft.situation==='Sonstiges'?`<label class="field"><span>Eigener Kontext</span><input id="other-situation" value="${esc(draft.situationDetail)}" placeholder="z. B. Behördentermin"></label>`:''}<label class="field"><span>Was geschieht gerade? (optional)</span><textarea id="event-text">${esc(draft.eventText)}</textarea></label>`);document.querySelectorAll('#situations .choice').forEach(b=>b.onclick=()=>{draft.situation=catalog.situations[+b.dataset.i].name;draft.situationDetail='';renderSituation()});document.getElementById('other-situation')?.addEventListener('input',e=>draft.situationDetail=e.target.value);document.getElementById('event-text').addEventListener('input',e=>draft.eventText=e.target.value);document.getElementById('next').onclick=async()=>{if(draft.situation==='Sonstiges'&&draft.situationDetail.trim()){const custom=draft.situationDetail.trim();if(!catalog.situations.some(s=>s.name.toLowerCase()===custom.toLowerCase())){catalog.situations.splice(catalog.situations.length-1,0,{name:custom,hint:'Eigener Kontext'});await saveCatalog()}draft.situation=custom}if(validateStep()){step++;renderDialog();window.scrollTo(0,0)}}}
function renderBody(){stepShell('Was spürst du im Körper?','Wähle eine oder mehrere Empfindungen und anschließend die Körperregionen.',`<h3>Empfindungen</h3><div class="chip-cloud" id="body">${catalog.body.map(x=>chip(x,draft.body.includes(x))).join('')}</div><h3>Wo spürst du es?</h3><div class="chip-cloud" id="regions">${catalog.regions.map(x=>chip(x,draft.regions.includes(x))).join('')}</div>`);bindChips('body',draft.body);bindChips('regions',draft.regions)}
function renderDirection(){const mirror=`<div class="mirror"><strong>Bisher:</strong> ${esc(draft.situation)} · ${esc(draft.body.join(', '))}${draft.regions.length?` in ${esc(draft.regions.join(', '))}`:''}</div>`;stepShell('Welche Grundrichtung hat dein Zustand?','Diese groben Achsen helfen, das Gefühlsfeld einzugrenzen.',mirror+choiceQuestion('Angenehm, neutral oder unangenehm?',['angenehm','neutral','unangenehm'],'valence')+choiceQuestion('Wie viel Energie ist da?',['wenig','mittel','viel'],'energy')+choiceQuestion('Wie wirkt dein Körper?',['ruhig','angespannt','aufgewühlt'],'arousal'));bindDirectionChoices()}
function choiceQuestion(q,opts,key){return `<h3>${q}</h3><div class="choice-grid" data-key="${key}">${opts.map(o=>`<button type="button" class="choice ${draft[key]===o?'selected':''}" data-v="${o}"><strong>${o}</strong></button>`).join('')}</div>`}
function bindDirectionChoices(){document.querySelectorAll('.choice-grid[data-key] .choice').forEach(b=>b.onclick=()=>{draft[b.parentElement.dataset.key]=b.dataset.v;renderDirection()})}
function renderImpulse(){stepShell('Was möchtest du gerade am liebsten tun?','Der Handlungsimpuls ist oft ein guter Hinweis. Mehrere Antworten sind möglich.',`<div class="chip-cloud" id="impulses">${catalog.impulses.map(x=>chip(x,draft.impulses.includes(x))).join('')}</div>`);bindChips('impulses',draft.impulses)}
function scoreSubs(){return catalog.sub.map(rule=>{let score=0;score+=rule.body.filter(x=>draft.body.includes(x)).length*3;if(rule.valence.includes(draft.valence))score+=2;if(rule.energy.includes(draft.energy))score+=1;if(rule.arousal.includes(draft.arousal))score+=2;score+=rule.impulses.filter(x=>draft.impulses.includes(x)).length*2;return {rule,score}}).sort((a,b)=>b.score-a.score)}
function renderSubfeelings(){const suggestions=scoreSubs().filter(x=>x.score>=3).slice(0,8).map(x=>x.rule);const list=showAllSubs?catalog.sub:suggestions;stepShell('Welche Wörter könnten passen?','Die Vorschläge werden aus Körper, Grundrichtung und Handlungsimpuls berechnet. Sie sind Hinweise, keine Diagnose.',`${suggestions.length?'<h3>Passende Vorschläge</h3>':'<div class="import-note">Für diese Kombination gibt es noch keine starken Vorschläge. Du kannst trotzdem alle Untergefühle anzeigen.</div>'}<div class="chip-cloud" id="subs">${list.map(x=>chip(x.name,draft.subs.includes(x.name),colorOf(x.main))).join('')}</div><button type="button" class="secondary main-toggle" id="toggle-subs">${showAllSubs?'Nur Vorschläge anzeigen':'Alle Untergefühle anzeigen'}</button>`);bindChips('subs',draft.subs);document.getElementById('toggle-subs').onclick=()=>{showAllSubs=!showAllSubs;renderSubfeelings()}}
function renderRelation(){const starters=['Ich fühle mich so, weil …','Das hängt zusammen mit …','Ich denke gerade …','Das erinnert mich an …','Ich wünsche mir …'];stepShell('Womit hängt dieses Gefühl zusammen?','Der Bezug hilft, Gefühl und Gedanken auseinanderzuhalten.',`<div class="sentence-starters">${starters.map(s=>`<button type="button" class="starter ${draft.relationStarter===s?'selected':''}" data-v="${esc(s)}">${esc(s)}</button>`).join('')}</div><label class="field"><span>${esc(draft.relationStarter)}</span><textarea id="relation">${esc(draft.relation)}</textarea></label><label class="field"><span>Welcher Gedanke ging dir durch den Kopf? (optional)</span><textarea id="thought">${esc(draft.thought)}</textarea></label>`);document.querySelectorAll('.starter').forEach(b=>b.onclick=()=>{draft.relationStarter=b.dataset.v;renderRelation()});document.getElementById('relation').oninput=e=>draft.relation=e.target.value;document.getElementById('thought').oninput=e=>draft.thought=e.target.value}
function intensityDescription(v){if(v===0)return ['Kaum spürbar','Ich spüre praktisch nichts davon.'];if(v<=2)return ['Im Hintergrund','Das Gefühl ist da, lässt sich aber leicht beiseiteschieben.'];if(v<=4)return ['Merklich','Das Gefühl ist wahrnehmbar, bestimmt mich aber noch nicht stark.'];if(v<=6)return ['Deutlich','Das Gefühl beeinflusst mein Erleben und meine Aufmerksamkeit spürbar.'];if(v<=8)return ['Sehr stark','Das Gefühl bestimmt gerade einen großen Teil meines Erlebens.'];return ['Überwältigend','Das Gefühl steht fast vollständig im Vordergrund und lässt sich kaum zur Seite schieben.']}
function renderIntensity(){const [title,text]=intensityDescription(+draft.intensity);stepShell('Wie stark bestimmt das Gefühl gerade dein Erleben?','Nutze nicht nur die Zahl. Frage dich auch: Wie leicht könnte ich das Gefühl gerade zur Seite schieben?',`<div class="scale"><input id="intensity" type="range" min="0" max="10" value="${draft.intensity}"><span class="score" id="intensity-value">${draft.intensity}</span></div><div class="intensity-help"><strong id="intensity-title">${title}</strong><span id="intensity-text">${text}</span><div class="intensity-anchors"><span>0<br>kaum</span><span>2<br>Hintergrund</span><span>5<br>deutlich</span><span>8<br>sehr stark</span><span>10<br>überwältigend</span></div></div>`);document.getElementById('intensity').oninput=e=>{draft.intensity=+e.target.value;document.getElementById('intensity-value').textContent=draft.intensity;const [a,b]=intensityDescription(draft.intensity);document.getElementById('intensity-title').textContent=a;document.getElementById('intensity-text').textContent=b}}
function deriveMain(){draft.candidates=[...new Set(draft.subs.map(s=>catalog.sub.find(x=>x.name===s)?.main).filter(Boolean))];if(draft.candidates.length===1)draft.chosenMain=draft.candidates[0];else if(!draft.candidates.includes(draft.chosenMain))draft.chosenMain=''}
function renderMain(){deriveMain();const candidates=draft.candidates;const list=showAllMain?catalog.main:catalog.main.filter(x=>candidates.includes(x.name));stepShell('Welches Hauptgefühl passt am ehesten?','Die App leitet mögliche Hauptgefühle aus deinen Untergefühlen ab. Deine eigene Einschätzung hat Vorrang.',`<div class="feeling-reminder"><span>Gewählte Untergefühle</span><strong>${esc(draft.subs.join(', '))}</strong></div>${candidates.length>1?`<div class="status ambiguous">Fühlst du dich eher ${candidates.map(esc).join(' oder ')}?</div>`:candidates.length===1?`<div class="status">Vorschlag: ${esc(candidates[0])}</div>`:'<div class="status open">Kein eindeutiges Hauptgefühl abgeleitet.</div>'}<div class="derived" id="mains">${list.map(x=>`<button type="button" class="emotion-card ${draft.chosenMain===x.name?'selected':''}" data-v="${esc(x.name)}" style="border-color:${x.color}"><strong>${esc(x.name)}</strong>${candidates.includes(x.name)?'<small>Aus deinen Untergefühlen abgeleitet</small>':'<small>Andere eigene Einschätzung</small>'}</button>`).join('')}</div><button type="button" class="secondary main-toggle" id="toggle-main">${showAllMain?'Nur Vorschläge anzeigen':'Anderes Hauptgefühl wählen'}</button>`);document.querySelectorAll('#mains .emotion-card').forEach(b=>b.onclick=()=>{draft.chosenMain=b.dataset.v;renderMain()});document.getElementById('toggle-main').onclick=()=>{showAllMain=!showAllMain;renderMain()}}
function renderConfidence(){stepShell('Wie gut passt diese Benennung gerade?','Die Sicherheit beschreibt nicht, ob du „richtig“ liegst, sondern wie stimmig sich das Wort im Moment anfühlt.',`<div class="feeling-reminder"><span>Bisher</span><strong>${esc(draft.chosenMain||'Noch offen')}</strong><small>${draft.candidates.length>1?`Ursprünglich möglich: ${esc(draft.candidates.join(', '))}`:draft.subs.length?`Untergefühle: ${esc(draft.subs.join(', '))}`:''}</small></div><div class="scale"><input id="confidence" type="range" min="0" max="100" step="5" value="${draft.confidence}"><span class="score" id="confidence-value">${draft.confidence}%</span></div><p class="muted">0 % = passt kaum · 50 % = möglicherweise · 100 % = trifft es sehr genau</p>`);document.getElementById('confidence').oninput=e=>{draft.confidence=+e.target.value;document.getElementById('confidence-value').textContent=`${draft.confidence}%`}}
function renderNeeds(){stepShell('Was brauchst du jetzt?','Wähle passende Bedürfnisse. Falls nichts passt, kannst du einen eigenen Begriff direkt ergänzen.',`<div class="chip-cloud" id="needs">${catalog.needs.map(x=>chip(x,draft.needs.includes(x))).join('')}</div><label class="field"><span>Eigenes Bedürfnis (optional)</span><input id="need-custom" value="${esc(draft.needCustom)}"></label><label class="field"><span>Wenn dein Gefühl sprechen könnte, was würde es sagen? (optional)</span><textarea id="feeling-message" placeholder="z. B. Ich brauche gerade Ruhe.">${esc(draft.feelingMessage)}</textarea></label>`);bindChips('needs',draft.needs);document.getElementById('need-custom').oninput=e=>draft.needCustom=e.target.value;document.getElementById('feeling-message').oninput=e=>draft.feelingMessage=e.target.value;document.getElementById('next').onclick=async()=>{const n=draft.needCustom.trim();if(n&&!catalog.needs.some(x=>x.toLowerCase()===n.toLowerCase())){catalog.needs.push(n);await saveCatalog()}if(n&&!draft.needs.includes(n))draft.needs.push(n);step=11;renderSummary();window.scrollTo(0,0)}}
function renderSummary(){const ambiguity=draft.candidates.length>1?'mehrdeutig':draft.chosenMain?'eindeutig':'offen';content.innerHTML=`<section class="panel"><div class="eyebrow">Zusammenfassung</div><h1>Dein Weg zur Gefühlsbenennung</h1><dl class="summary-grid"><dt>Situation</dt><dd>${esc(draft.situation)}${draft.eventText?`<br>${esc(draft.eventText)}`:''}</dd><dt>Körper</dt><dd>${esc(draft.body.join(', '))}${draft.regions.length?` · ${esc(draft.regions.join(', '))}`:''}</dd><dt>Grundrichtung</dt><dd>${esc([draft.valence,draft.energy+' Energie',draft.arousal].join(' · '))}</dd><dt>Handlungsimpuls</dt><dd>${esc(draft.impulses.join(', ')||'—')}</dd><dt>Untergefühle</dt><dd>${esc(draft.subs.join(', '))}</dd><dt>${esc(draft.relationStarter||'Bezug')}</dt><dd>${esc(draft.relation||'—')}</dd><dt>Gedanke</dt><dd>${esc(draft.thought||'—')}</dd><dt>Intensität</dt><dd>${draft.intensity}/10 · ${esc(intensityDescription(draft.intensity)[0])}</dd><dt>Mögliche Hauptgefühle</dt><dd>${esc(draft.candidates.join(', ')||'—')}</dd><dt>Gewähltes Gefühl</dt><dd><strong>${esc(draft.chosenMain||'Noch offen')}</strong></dd><dt>Sicherheit</dt><dd>${draft.confidence}%</dd><dt>Bedürfnis</dt><dd>${esc(draft.needs.join(', ')||'—')}</dd><dt>Das Gefühl sagt</dt><dd>${esc(draft.feelingMessage||'—')}</dd></dl><div class="status ${ambiguity==='mehrdeutig'?'ambiguous':ambiguity==='offen'?'open':''}">${ambiguity==='mehrdeutig'?'Du hast mehrere mögliche Gefühlsbereiche unterschieden. Diese Mehrdeutigkeit wird mitgespeichert.':ambiguity==='offen'?'Eine offene Benennung ist ebenfalls eine genaue Beobachtung.':'Die Benennung war in diesem Durchgang eindeutig.'}</div><div class="summary-actions"><button type="button" class="primary" id="save-summary">Speichern & neuer Eintrag</button><button type="button" class="ghost" id="summary-back">Zurück</button></div></section>`;document.getElementById('summary-back').onclick=()=>{step=10;renderDialog()};document.getElementById('save-summary').onclick=async()=>{const entry={...clone(draft),id:editingId||crypto.randomUUID(),ambiguity,updatedAt:new Date().toISOString()};await saveEntry(entry);editingId=null;draft=newDraft();step=1;showAllSubs=false;showAllMain=false;toast('Eintrag gespeichert.');setPage('dialog')}}

function renderHistory(){
  const cards=entries.length?entries.map(e=>`<article class="panel history-card" data-view="${e.id}"><button type="button" class="open-detail" data-view="${e.id}"><div class="step-head"><div><div class="eyebrow">${new Date(e.createdAt).toLocaleString('de-DE')}</div><h2>${esc(e.chosenMain||'Noch nicht bestimmt')}</h2></div><span class="status ${e.ambiguity==='mehrdeutig'?'ambiguous':e.ambiguity==='offen'?'open':''}">${esc(e.ambiguity||'offen')}</span></div><p>${esc(e.situation)} · ${esc((e.body||[]).join(', '))}</p><p><strong>${esc((e.subs||[]).join(', '))}</strong></p><p class="muted">Sicherheit ${e.confidence||0}% · Intensität ${e.intensity||0}/10</p></button><div class="entry-actions"><button class="secondary" data-details="${e.id}">Details</button><button class="secondary" data-edit="${e.id}">Bearbeiten</button><button class="danger" data-delete="${e.id}">Löschen</button></div></article>`).join(''):'<div class="empty">Noch keine Einträge gespeichert.</div>';
  shell('Verlauf','Tippe einen Eintrag an, um alle gespeicherten Angaben zu sehen.',`<section class="panel"><h2>Datensicherung</h2><p class="muted">Exportiere alle Einträge als CSV oder Excel. Beim Import werden passende Spalten übernommen und neue Datensätze in Verlauf und Auswertung aufgenommen.</p><div class="button-row"><button class="secondary" id="export-csv">CSV exportieren</button><button class="secondary" id="export-xlsx">Excel exportieren</button><button class="secondary" id="import-data">CSV / Excel importieren</button></div><div id="import-report"></div></section>${cards}`);
  document.querySelectorAll('[data-view],[data-details]').forEach(b=>b.onclick=e=>{e.stopPropagation();const id=b.dataset.view||b.dataset.details;const entry=entries.find(x=>x.id===id);if(entry)openEntryDetails(entry)});
  document.querySelectorAll('[data-edit]').forEach(b=>b.onclick=e=>{e.stopPropagation();const entry=entries.find(x=>x.id===b.dataset.edit);draft=normalizeEntry(entry);editingId=entry.id;step=1;setPage('dialog')});
  document.querySelectorAll('[data-delete]').forEach(b=>b.onclick=e=>{e.stopPropagation();openConfirm('Eintrag löschen?','Dieser Eintrag wird dauerhaft entfernt.',async()=>{await idbDelete('entries',b.dataset.delete);entries=await idbAll('entries');entries.sort((a,b)=>new Date(b.createdAt)-new Date(a.createdAt));renderHistory()})});
  document.getElementById('export-csv').onclick=exportEntriesCsv;
  document.getElementById('export-xlsx').onclick=exportEntriesXlsx;
  document.getElementById('import-data').onclick=()=>dataFile.click();
}

function normalizeEntry(e={}){return {...newDraft(),...clone(e),body:Array.isArray(e.body)?e.body:[],regions:Array.isArray(e.regions)?e.regions:[],impulses:Array.isArray(e.impulses)?e.impulses:[],subs:Array.isArray(e.subs)?e.subs:[],candidates:Array.isArray(e.candidates)?e.candidates:[],needs:Array.isArray(e.needs)?e.needs:[]}}
function detailRow(label,value){return `<dt>${esc(label)}</dt><dd>${esc(value||'—')}</dd>`}
function openEntryDetails(raw){const e=normalizeEntry(raw);modalBody.innerHTML=`<h2>${esc(e.chosenMain||'Noch nicht bestimmt')}</h2><div class="eyebrow">${new Date(e.createdAt).toLocaleString('de-DE')}</div><dl class="detail-grid">${detailRow('Situation',e.situation)}${detailRow('Was geschah?',e.eventText)}${detailRow('Körperempfindungen',e.body.join(', '))}${detailRow('Körperregionen',e.regions.join(', '))}${detailRow('Grundrichtung',[e.valence,e.energy?e.energy+' Energie':'',e.arousal].filter(Boolean).join(' · '))}${detailRow('Handlungsimpulse',e.impulses.join(', '))}${detailRow('Untergefühle',e.subs.join(', '))}${detailRow(e.relationStarter||'Bezug',e.relation)}${detailRow('Gedanke',e.thought)}${detailRow('Intensität',`${e.intensity}/10 · ${intensityDescription(e.intensity)[0]}`)}${detailRow('Mögliche Hauptgefühle',e.candidates.join(', '))}${detailRow('Gewähltes Gefühl',e.chosenMain)}${detailRow('Benennung',e.ambiguity)}${detailRow('Sicherheit',`${e.confidence}%`)}${detailRow('Bedürfnisse',e.needs.join(', '))}${detailRow('Das Gefühl sagt',e.feelingMessage)}</dl><div class="detail-actions"><button value="cancel" class="ghost">Schließen</button><button type="button" class="primary" id="detail-edit">Bearbeiten</button></div>`;modal.showModal();document.getElementById('detail-edit').onclick=()=>{modal.close();draft=e;editingId=e.id;step=1;setPage('dialog')}}

function downloadBlob(blob,name){const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=name;document.body.appendChild(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(a.href),1000)}
function csvEscape(v){const t=String(v??'');return `"${t.replaceAll('"','""')}"`}
function entryHeaders(){return ['ID','Zeitpunkt','Situation','Was geschah?','Körperempfindungen','Körperregionen','Grundrichtung','Energie','Körperzustand','Handlungsimpulse','Untergefühle','Satzanfang','Bezug','Gedanke','Intensität','Mögliche Hauptgefühle','Gewähltes Hauptgefühl','Benennung','Sicherheit','Bedürfnisse','Das Gefühl sagt']}
function entryRow(e){e=normalizeEntry(e);return [e.id,e.createdAt,e.situation,e.eventText,e.body.join(' | '),e.regions.join(' | '),e.valence,e.energy,e.arousal,e.impulses.join(' | '),e.subs.join(' | '),e.relationStarter,e.relation,e.thought,e.intensity,e.candidates.join(' | '),e.chosenMain,e.ambiguity,e.confidence,e.needs.join(' | '),e.feelingMessage]}
function exportEntriesCsv(){const rows=[entryHeaders(),...entries.slice().reverse().map(entryRow)];const text='\uFEFF'+rows.map(r=>r.map(csvEscape).join(';')).join('\r\n');downloadBlob(new Blob([text],{type:'text/csv;charset=utf-8'}),`gefuehlskompass-daten-${new Date().toISOString().slice(0,10)}.csv`)}
async function exportEntriesXlsx(){if(!window.JSZip){toast('Excel-Modul nicht geladen.');return}const rows=[entryHeaders(),...entries.slice().reverse().map(entryRow)];const zip=new JSZip();zip.file('[Content_Types].xml','<?xml version="1.0" encoding="UTF-8"?><Types xmlns="http://schemas.openxmlformats.org/package/2006/content-types"><Default Extension="rels" ContentType="application/vnd.openxmlformats-package.relationships+xml"/><Default Extension="xml" ContentType="application/xml"/><Override PartName="/xl/workbook.xml" ContentType="application/vnd.openxmlformats-officedocument.spreadsheetml.sheet.main+xml"/><Override PartName="/xl/worksheets/sheet1.xml" ContentType="application/vnd.openxmlformats-officedocument.spreadsheetml.worksheet+xml"/></Types>');zip.folder('_rels').file('.rels','<?xml version="1.0" encoding="UTF-8"?><Relationships xmlns="http://schemas.openxmlformats.org/package/2006/relationships"><Relationship Id="rId1" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/officeDocument" Target="xl/workbook.xml"/></Relationships>');zip.folder('xl').file('workbook.xml','<?xml version="1.0" encoding="UTF-8"?><workbook xmlns="http://schemas.openxmlformats.org/spreadsheetml/2006/main" xmlns:r="http://schemas.openxmlformats.org/officeDocument/2006/relationships"><sheets><sheet name="Einträge" sheetId="1" r:id="rId1"/></sheets></workbook>');zip.folder('xl').folder('_rels').file('workbook.xml.rels','<?xml version="1.0" encoding="UTF-8"?><Relationships xmlns="http://schemas.openxmlformats.org/package/2006/relationships"><Relationship Id="rId1" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/worksheet" Target="worksheets/sheet1.xml"/></Relationships>');const letters=n=>{let x='',i=n+1;while(i){x=String.fromCharCode(65+(i-1)%26)+x;i=Math.floor((i-1)/26)}return x};const sheet=`<?xml version="1.0" encoding="UTF-8"?><worksheet xmlns="http://schemas.openxmlformats.org/spreadsheetml/2006/main"><sheetData>${rows.map((r,ri)=>`<row r="${ri+1}">${r.map((v,ci)=>`<c r="${letters(ci)}${ri+1}" t="inlineStr"><is><t xml:space="preserve">${xmlEsc(v)}</t></is></c>`).join('')}</row>`).join('')}</sheetData></worksheet>`;zip.folder('xl').folder('worksheets').file('sheet1.xml',sheet);downloadBlob(await zip.generateAsync({type:'blob',mimeType:'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet'}),`gefuehlskompass-daten-${new Date().toISOString().slice(0,10)}.xlsx`)}
function xmlEsc(v){return String(v??'').replaceAll('&','&amp;').replaceAll('<','&lt;').replaceAll('>','&gt;').replaceAll('"','&quot;')}
function splitList(v){return String(v||'').split(/[|,;]/).map(x=>x.trim()).filter(Boolean)}
function parseCsv(text){text=text.replace(/^\uFEFF/,'');const delimiter=(text.split(/\r?\n/,1)[0].match(/;/g)||[]).length>=(text.split(/\r?\n/,1)[0].match(/,/g)||[]).length?';':',';const out=[],row=[];let cell='',quote=false;for(let i=0;i<text.length;i++){const c=text[i];if(c==='"'&&quote&&text[i+1]==='"'){cell+='"';i++}else if(c==='"')quote=!quote;else if(c===delimiter&&!quote){row.push(cell);cell=''}else if((c==='\n'||c==='\r')&&!quote){if(c==='\r'&&text[i+1]==='\n')i++;row.push(cell);cell='';if(row.some(x=>x.trim()))out.push(row.splice(0))}else cell+=c}row.push(cell);if(row.some(x=>x.trim()))out.push(row);return out}
async function parseXlsx(file){const zip=await JSZip.loadAsync(await file.arrayBuffer());const shared=[];const sharedFile=zip.file('xl/sharedStrings.xml');if(sharedFile){const doc=new DOMParser().parseFromString(await sharedFile.async('text'),'application/xml');doc.querySelectorAll('si').forEach(si=>shared.push(si.textContent||''))}const sheetFile=zip.file('xl/worksheets/sheet1.xml');if(!sheetFile)throw new Error('Kein erstes Tabellenblatt gefunden.');const doc=new DOMParser().parseFromString(await sheetFile.async('text'),'application/xml');return [...doc.querySelectorAll('row')].map(row=>{const map={};let max=-1;row.querySelectorAll('c').forEach(c=>{const ref=c.getAttribute('r')||'';const letters=(ref.match(/[A-Z]+/)||['A'])[0];let col=0;for(const ch of letters)col=col*26+ch.charCodeAt(0)-64;col--;max=Math.max(max,col);let value=c.querySelector('is t')?.textContent??c.querySelector('v')?.textContent??'';if(c.getAttribute('t')==='s')value=shared[Number(value)]??'';map[col]=value});return Array.from({length:max+1},(_,i)=>map[i]??'')})}
function keyName(v){return String(v||'').trim().toLowerCase().replaceAll('ä','ae').replaceAll('ö','oe').replaceAll('ü','ue').replaceAll('ß','ss').replace(/[^a-z0-9]/g,'')}
function parseImportedRows(rows){if(rows.length<2)return {items:[],invalid:0,duplicates:0};const headers=rows[0].map(keyName),idx=(...names)=>names.map(keyName).map(n=>headers.indexOf(n)).find(i=>i>=0)??-1,val=(r,i)=>i>=0&&i<r.length?String(r[i]??'').trim():'';const cols={id:idx('ID'),time:idx('Zeitpunkt','Datum'),situation:idx('Situation'),event:idx('Was geschah?','Ereignis'),body:idx('Körperempfindungen','Körper'),regions:idx('Körperregionen'),valence:idx('Grundrichtung'),energy:idx('Energie'),arousal:idx('Körperzustand'),impulses:idx('Handlungsimpulse'),subs:idx('Untergefühle'),starter:idx('Satzanfang'),relation:idx('Bezug'),thought:idx('Gedanke'),intensity:idx('Intensität'),candidates:idx('Mögliche Hauptgefühle'),main:idx('Gewähltes Hauptgefühl','Hauptgefühl','Gefühl'),ambiguity:idx('Benennung','Mehrdeutig'),confidence:idx('Sicherheit'),needs:idx('Bedürfnisse'),message:idx('Das Gefühl sagt')};if(cols.time<0||cols.situation<0)return {items:[],invalid:rows.length-1,duplicates:0,error:'Zeitpunkt und Situation müssen vorhanden sein.'};const existing=new Set(entries.map(e=>`${e.createdAt}|${e.situation}|${e.chosenMain}|${e.relation}`.toLowerCase()));let invalid=0,duplicates=0;const items=[];rows.slice(1).forEach((r,n)=>{const createdAt=parseImportDate(val(r,cols.time));if(!createdAt||!val(r,cols.situation)){invalid++;return}const e=normalizeEntry({id:val(r,cols.id)||crypto.randomUUID(),createdAt,situation:val(r,cols.situation),eventText:val(r,cols.event),body:splitList(val(r,cols.body)),regions:splitList(val(r,cols.regions)),valence:val(r,cols.valence),energy:val(r,cols.energy),arousal:val(r,cols.arousal),impulses:splitList(val(r,cols.impulses)),subs:splitList(val(r,cols.subs)),relationStarter:val(r,cols.starter)||'Ich fühle mich so, weil …',relation:val(r,cols.relation),thought:val(r,cols.thought),intensity:Number(val(r,cols.intensity))||5,candidates:splitList(val(r,cols.candidates)),chosenMain:val(r,cols.main),ambiguity:val(r,cols.ambiguity)||'offen',confidence:Number(String(val(r,cols.confidence)).replace('%',''))||0,needs:splitList(val(r,cols.needs)),feelingMessage:val(r,cols.message)});const key=`${e.createdAt}|${e.situation}|${e.chosenMain}|${e.relation}`.toLowerCase();if(existing.has(key)){duplicates++;return}existing.add(key);items.push(e)});return {items,invalid,duplicates}}
function parseImportDate(v){const s=String(v||'').trim();if(!s)return null;let d=new Date(s);if(!Number.isNaN(d.getTime()))return d.toISOString();let m=s.match(/^(\d{1,2})\.(\d{1,2})\.(\d{4})(?:\s+(\d{1,2}):(\d{2})(?::(\d{2}))?)?$/);if(m){d=new Date(+m[3],+m[2]-1,+m[1],+(m[4]||0),+(m[5]||0),+(m[6]||0));return d.toISOString()}const serial=Number(s);if(Number.isFinite(serial)&&serial>20000){d=new Date(Date.UTC(1899,11,30)+serial*86400000);return d.toISOString()}return null}
dataFile.onchange=async()=>{const file=dataFile.files[0];if(!file)return;try{const rows=file.name.toLowerCase().endsWith('.xlsx')?await parseXlsx(file):parseCsv(await file.text());const result=parseImportedRows(rows);if(result.error)throw new Error(result.error);for(const e of result.items)await idbPut('entries',e);entries=await idbAll('entries');entries.sort((a,b)=>new Date(b.createdAt)-new Date(a.createdAt));renderHistory();document.getElementById('import-report').innerHTML=`<div class="import-report"><strong>${result.items.length}</strong> importiert · ${result.duplicates} Dubletten · ${result.invalid} fehlerhafte Zeilen</div>`}catch(e){toast(`Datenimport fehlgeschlagen: ${e.message}`)}finally{dataFile.value=''}}

function renderStats(){const total=Math.max(1,entries.length);const counts={};entries.forEach(e=>counts[e.chosenMain||'Offen']=(counts[e.chosenMain||'Offen']||0)+1);let angle=0;const segments=Object.entries(counts).map(([name,n])=>{const start=angle;angle+=n/total*360;return `${colorOf(name)} ${start}deg ${angle}deg`}).join(',');const ambiguous=entries.filter(e=>e.ambiguity==='mehrdeutig').length;const open=entries.filter(e=>e.ambiguity==='offen').length;const avg=entries.length?Math.round(entries.reduce((a,e)=>a+(e.confidence||0),0)/entries.length):0;shell('Auswertung','Die ersten funktionalen Auswertungen zeigen Verteilung, Sicherheit und Mehrdeutigkeit.',`<div class="stats-grid"><section class="panel chart-box"><h2>Gefühlsverteilung</h2><div class="pie-wrap"><div class="pie" style="background:conic-gradient(${segments||'#ddd 0 360deg'})"></div></div><div class="legend">${Object.entries(counts).map(([n,c])=>`<div class="legend-row"><span class="dot" style="background:${colorOf(n)}"></span><span>${esc(n)}</span><strong>${c}</strong></div>`).join('')||'<p>Noch keine Daten.</p>'}</div></section><section class="panel chart-box"><h2>Lernindikatoren</h2><p><strong>${avg}%</strong> durchschnittliche Sicherheit</p><div class="bar-track"><div class="bar" style="width:${avg}%"></div></div><p><strong>${ambiguous}</strong> mehrdeutige und <strong>${open}</strong> offene Einträge.</p><p class="muted">Später kann hier die Entwicklung nach Woche und Monat sowie häufige Gefühlspaare ergänzt werden.</p></section></div>`)}

function renderCatalog(){shell('Katalog & Beziehungen','Hier pflegst du Begriffe und die Regeln, aus denen die Vorschläge berechnet werden.',`${catalogBlock('Situationen','situations',catalog.situations.map(x=>x.name))}${catalogBlock('Körperempfindungen','body',catalog.body)}${catalogBlock('Körperregionen','regions',catalog.regions)}${catalogBlock('Handlungsimpulse','impulses',catalog.impulses)}${catalogBlock('Bedürfnisse','needs',catalog.needs)}${mainCatalog()}${relationshipCatalog()}<section class="catalog-section"><h2>Sicherung und Bearbeitung am Rechner</h2><p class="muted">Der JSON-Export enthält alle Listen, Farben und Beziehungen. Du kannst die Datei in einem Texteditor bearbeiten und anschließend wieder importieren.</p><div class="button-row"><button class="secondary" id="export-rel">Katalog & Beziehungen exportieren</button><button class="secondary" id="import-rel">Katalog & Beziehungen importieren</button><button class="danger" id="reset-catalog">Standardkatalog wiederherstellen</button></div></section><p class="version-note">Gefühlskompass · Phase 2 · Version ${VERSION}</p>`);bindCatalog();document.getElementById('export-rel').onclick=exportCatalog;document.getElementById('import-rel').onclick=()=>catalogFile.click();document.getElementById('reset-catalog').onclick=()=>openConfirm('Katalog zurücksetzen?','Alle eigenen Begriffe und Beziehungen werden durch die Standardwerte ersetzt.',async()=>{catalog=clone(defaults);await saveCatalog();renderCatalog();toast('Katalog zurückgesetzt.')})}
function catalogBlock(title,key,items){return `<section class="catalog-section"><h2>${title}</h2><div class="catalog-list">${items.map((x,i)=>`<div class="catalog-item"><span>${esc(x)}</span><button data-remove="${key}" data-i="${i}">Entfernen</button></div>`).join('')}</div><div class="button-row"><button class="secondary" data-add="${key}">+ Eintrag</button></div></section>`}
function mainCatalog(){return `<section class="catalog-section"><h2>Hauptgefühle</h2><div class="catalog-list">${catalog.main.map((x,i)=>`<div class="catalog-item"><span><span class="dot" style="display:inline-block;background:${x.color};margin-right:8px"></span>${esc(x.name)}</span><button data-remove="main" data-i="${i}">Entfernen</button></div>`).join('')}</div><div class="button-row"><button class="secondary" data-add="main">+ Hauptgefühl</button></div></section>`}
function relationshipCatalog(){return `<section class="catalog-section"><h2>Untergefühle und Vorschlagsregeln</h2><p class="muted">Öffne ein Untergefühl, um seine Zuordnung zu Körper, Grundrichtung und Handlungsimpuls zu bearbeiten.</p><div class="relation-editor">${catalog.sub.map((r,i)=>`<details class="rule-card"><summary>${esc(r.name)} → ${esc(r.main)}</summary><div class="button-row"><button class="secondary" data-edit-rule="${i}">Regel bearbeiten</button><button class="danger" data-remove-rule="${i}">Entfernen</button></div><p class="muted">Körper: ${esc(r.body.join(', ')||'—')}<br>Richtung: ${esc([...r.valence,...r.energy,...r.arousal].join(', ')||'—')}<br>Impulse: ${esc(r.impulses.join(', ')||'—')}</p></details>`).join('')}</div><div class="button-row"><button class="secondary" id="add-rule">+ Untergefühl mit Regel</button></div></section>`}
function bindCatalog(){document.querySelectorAll('[data-remove]').forEach(b=>b.onclick=async()=>{const key=b.dataset.remove,i=+b.dataset.i;if(key==='situations')catalog.situations.splice(i,1);else catalog[key].splice(i,1);await saveCatalog();renderCatalog()});document.querySelectorAll('[data-add]').forEach(b=>b.onclick=()=>openSimpleAdd(b.dataset.add));document.querySelectorAll('[data-edit-rule]').forEach(b=>b.onclick=()=>openRuleEditor(+b.dataset.editRule));document.querySelectorAll('[data-remove-rule]').forEach(b=>b.onclick=async()=>{catalog.sub.splice(+b.dataset.removeRule,1);await saveCatalog();renderCatalog()});document.getElementById('add-rule').onclick=()=>openRuleEditor(-1)}
function openSimpleAdd(key){const isMain=key==='main';modalBody.innerHTML=`<h2>Eintrag hinzufügen</h2><label class="field"><span>Bezeichnung</span><input id="m-name"></label>${key==='situations'?'<label class="field"><span>Kurze Erläuterung</span><input id="m-hint"></label>':''}${isMain?'<label class="field"><span>Farbe</span><input id="m-color" type="color" value="#789c95"></label>':''}<div class="button-row"><button value="cancel" class="ghost">Abbrechen</button><button value="default" class="primary" id="m-save">Speichern</button></div>`;modal.showModal();document.getElementById('m-save').onclick=async e=>{e.preventDefault();const n=document.getElementById('m-name').value.trim();if(!n)return;if(key==='situations')catalog.situations.push({name:n,hint:document.getElementById('m-hint').value.trim()||'Eigener Kontext'});else if(isMain)catalog.main.push({name:n,color:document.getElementById('m-color').value});else addUnique(catalog[key],n);await saveCatalog();modal.close();renderCatalog()}}
function checks(title,items,selected,prefix){return `<fieldset><legend>${title}</legend><div class="rule-grid">${items.map((x,i)=>`<label class="mini-check"><input type="checkbox" name="${prefix}" value="${esc(x)}" ${selected.includes(x)?'checked':''}>${esc(x)}</label>`).join('')}</div></fieldset>`}
function openRuleEditor(index){const old=index>=0?catalog.sub[index]:{name:'',main:catalog.main[0]?.name||'',body:[],valence:[],energy:[],arousal:[],impulses:[]};modalBody.innerHTML=`<h2>${index>=0?'Vorschlagsregel bearbeiten':'Untergefühl und Regel anlegen'}</h2><label class="field"><span>Untergefühl</span><input id="r-name" value="${esc(old.name)}"></label><label class="field"><span>Hauptgefühl</span><select id="r-main">${catalog.main.map(x=>`<option ${x.name===old.main?'selected':''}>${esc(x.name)}</option>`).join('')}</select></label>${checks('Körperempfindungen',catalog.body,old.body,'r-body')}${checks('Grundrichtung: angenehm / neutral / unangenehm',['angenehm','neutral','unangenehm'],old.valence,'r-valence')}${checks('Energie',['wenig','mittel','viel'],old.energy,'r-energy')}${checks('Körperzustand',['ruhig','angespannt','aufgewühlt'],old.arousal,'r-arousal')}${checks('Handlungsimpulse',catalog.impulses,old.impulses,'r-impulses')}<div class="button-row"><button value="cancel" class="ghost">Abbrechen</button><button value="default" class="primary" id="r-save">Speichern</button></div>`;modal.showModal();document.getElementById('r-save').onclick=async e=>{e.preventDefault();const val=name=>[...modalBody.querySelectorAll(`input[name="${name}"]:checked`)].map(x=>x.value);const rule={name:document.getElementById('r-name').value.trim(),main:document.getElementById('r-main').value,body:val('r-body'),valence:val('r-valence'),energy:val('r-energy'),arousal:val('r-arousal'),impulses:val('r-impulses')};if(!rule.name)return;if(index>=0)catalog.sub[index]=rule;else catalog.sub.push(rule);await saveCatalog();modal.close();renderCatalog()}}
function exportCatalog(){const blob=new Blob([JSON.stringify({app:'Gefühlskompass',version:VERSION,exportedAt:new Date().toISOString(),catalog},null,2)],{type:'application/json'});const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=`gefuehlskompass-katalog-beziehungen-${new Date().toISOString().slice(0,10)}.json`;a.click();URL.revokeObjectURL(a.href)}
catalogFile.onchange=async()=>{const file=catalogFile.files[0];if(!file)return;try{const data=JSON.parse(await file.text());const incoming=data.catalog||data;if(!Array.isArray(incoming.sub)||!Array.isArray(incoming.main)||!Array.isArray(incoming.body))throw new Error('Struktur unvollständig');catalog=incoming;await saveCatalog();renderCatalog();toast('Katalog und Beziehungen importiert.')}catch(e){toast(`Import fehlgeschlagen: ${e.message}`)}finally{catalogFile.value=''}}
function openConfirm(title,text,yes){modalBody.innerHTML=`<h2>${esc(title)}</h2><p>${esc(text)}</p><div class="button-row"><button value="cancel" class="ghost">Abbrechen</button><button value="default" class="danger" id="confirm-yes">Bestätigen</button></div>`;modal.showModal();document.getElementById('confirm-yes').onclick=e=>{e.preventDefault();modal.close();yes()}}

async function init(){db=await openDb();catalog=await idbGet('meta','catalog')||clone(defaults);await idbPut('meta',catalog,'catalog');entries=await idbAll('entries');entries.sort((a,b)=>new Date(b.createdAt)-new Date(a.createdAt));document.querySelectorAll('.nav').forEach(b=>b.onclick=()=>setPage(b.dataset.page));document.getElementById('restart').onclick=()=>openConfirm('Dialog neu starten?','Die bisherigen Angaben dieses Durchgangs werden verworfen.',()=>{editingId=null;draft=newDraft();step=1;showAllSubs=false;showAllMain=false;setPage('dialog')});render();if('serviceWorker' in navigator){try{const reg=await navigator.serviceWorker.register('./sw.js?v=0.21',{updateViaCache:'none'});await reg.update()}catch(e){console.warn(e)}}}
init().catch(e=>{content.innerHTML=`<section class="panel"><h1>Startfehler</h1><p>${esc(e.message)}</p></section>`});
